### ISSUE TITLE
Build system issue while cross-compiling

### ISSUE THREAD

**Issue by RomainNaour** [HoerTech-gGmbH/openMHA#15]
Is there any plan to use a build system that is cross-compilation friendly ?
I would suggest using CMake instead of hand written Makefiles and configure script.

For now, the configure script detect my host gcc instead of the target toolchain (ARM):
```
PLATFORM=linux
DYNAMIC_LIB_EXT=.so
GCC_VER=-8
BUILD_DIR=x86_64-linux-gcc-8
ARCH=x86_64
PREFIX=/usr
WITH_ALSA=yes
WITH_JACK=yes
SSE+=-msse -msse2 -mfpmath=sse
OPTIM=-O3 $(SSE) -ffast-math -fomit-frame-pointer -fno-finite-math-only
CXXFLAGS+=-Wall -Werror -std=c++11 -fPIC $(OPTIM)
CFLAGS+=-Wall -Werror -std=gnu11 -fPIC $(OPTIM)
```
The build fail latter while cross-compiling the bundled version of fftw (2.1.5)

I attended to the ELCE openMHA presentation and I wanted to try to add openMHA to Buildroot.
I'd like to help on the build system :)

Best regards,
Romain

**Comment by tobiasherzke** [comment]
Hi Romain, thank you for your interest.

In the next release we can reactivate the option to cross-compile for arm.

We are now mostly compiling natively on the target platform, and that will most likely remain our focus. Will give short instructions for experts here when the next release is out. ETA of next relase: next week.

**Comment by tobiasherzke** [comment]
With the current release 4.7.0 you can cross-compile for arm after configuring with --arch=armhf. The build system expects to be able to call the cross-compiler as `arm-linux-gnueabihf-g++-<version>` on the PATH. You need to install at least the libraries libsndfile and its dependencies, libportaudio and its dependencies libasound, libjack in your cross-build environment so that you can compile and link arm binaries against these libraries.
Configure the openMHA build as `./configure --arch=armhf --with-osc=no --with-lsl=no` and call make. (You could also install liblo and liblsl in the cross-build environment and omit the --with...=no parameters).
Hope this helps.
