### ISSUE TITLE
MHAIOalsa Read Failed error while connected to MATLAB

### ISSUE THREAD

**Issue by JEEaton001** [HoerTech-gGmbH/openMHA#29]
I have openMHA installed and running, and I have been able to get a live passthrough working with the iolib: MHAIOalsa. Though once I connect openMHA to MATLAB over Ethernet it will start displaying read and write errors when I try to change parameters in the filter menu. Is there a way around this error? Also is the fitting dialog not supposed to make live changes to openMHA? 

![alsaReadError](https://user-images.githubusercontent.com/37002668/59635243-f6a32480-910d-11e9-9f25-87f9e267b263.JPG)

**Comment by tobiasherzke** [comment]
Which sound card are you using and how is it configured?

**Comment by JEEaton001** [comment]
It is a custom sound card using the audio codek. sampling rate of 48000Hz, format is S32_LE, 2 channels. That fallows the Linux simple sound card design. I can pass-through, play, and record sound using arecord and aplay, and have not had an issue with missing frames before.

**Comment by tobiasherzke** [comment]
It is exciting that you want to use your own custom sound card with openMHA. Please keep us informed about your progress.

As you can see in the source code https://github.com/HoerTech-gGmbH/openMHA/blob/master/mha/plugins/io/src/MHAIOalsa.cpp#L148, we are using blocking alsa I/O. The alsa library documentation states at https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga4c2c7bd26cf221268d59dc3bbeb9c048 for the snd_pcm_readi function:
> If the blocking behaviour was selected and it is running, then routine waits until all requested frames are filled. The returned number of frames can be less only if a signal or underrun occurred.

So it seems you have xruns when network traffic occurs. If I remember correctly we do not do XRun recovery in the MHAIOalsa alsa I/O library. Your options:

- Avoid generating xruns. You can probably optimize your system by using a lowlatency or a realtime kernel, configure interrupt and thread priorities of the device drivers and sound processing applications with rtirq and explicit setting of scheduler and priority of MHAIOalsa or Jack. Please google for optimizing a linux system for low-latency audio processing.
- Use MHAIOJack and a Jack server to talk to the sound card. Jack does xrun recovery.
- Finally, if you find anything that we could change in MHAIOalsa that benefits your sound card, be sure to fire us a pull request with your changes, then we will consider if this change is applicable to a wider range of sound cards and should be included in openMHA.

> Also is the fitting dialog not supposed to make live changes to openMHA?

Yes, you can make live changes in a running openMHA. Of course, your system needs to be able to handle signal processing and network communication simultaneously, otherwise xruns may occur.
