### ISSUE TITLE
cannot find the openMHA libraries and openMHA bin directory

### ISSUE THREAD

**Issue by dhanashri-innovision** [HoerTech-gGmbH/openMHA#34]
Hi,
I am trying to compile the openmha through mingw.
in the compilation document, it is written the 
copy openMHA libraries into the openMHA bin directory: ```mv lib/* bin/```

but there are no such folders in openMHA.
should I create them?

**Comment by tobiasherzke** [comment]
Please ask support questions like this on the forum, https://forum.openmha.org/

These directories are created by the previous step of the compilation instructions.

**Comment by tobiasherzke** [comment]
Please not that we also provide a windows installer with precompiled binaries and plugins, so that there is rarely a need to compile openMHA yourself. Please refer to the openMHA releases, https://github.com/HoerTech-gGmbH/openMHA/releases. You can find installation instructions here https://github.com/HoerTech-gGmbH/openMHA/blob/master/INSTALLATION.md and a getting-started guide here: http://www.openmha.org/docs/openMHA_starting_guide.pdf.

**Comment by dhanashri-innovision** [comment]
thanks
