### ISSUE TITLE
Document that minimum CPU requirement for binary ARM32 packages is ARMv7

### ISSUE THREAD

**Issue by MikeBarcl** [HoerTech-gGmbH/openMHA#46]
Hi, I've fallen at the first hurdle. mha --interactive works fine on my laptop. But after apparently successful installation on the raspberry pi zero (running raspbian light) it returns [Illegal instruction]. 

Any tips?

Many thanks
Mike

**Comment by tobiasherzke** [comment]
The openMHA binary packages that we distribute for 32-bit ARM are compiled for computers which have at least ARMv7 CPUs. They will not work on ARMv6 CPUs. For the different Raspberry Pis, this means they should work for Raspberry Pi 2, 3, and 4, but not for Raspberry Pi zero and 1.

You can still compile openMHA for the Raspberry Pi zero yourself. Follow our compilation instructions for Linux on the zero, with the following change: instead of executing `./configure && make` in a single step as suggested in file COMPILATION.md, you would execute

    ./configure
    # Use an editor to modify the generated file config.mk, e.g. "nano", or use another editor of your choice:
    nano config.mk # Delete the line containing "SSE+=-mcpu=cortex-a8 -mfloat-abi=hard -mfpu=neon"
    # after saving the modified file:
    make


We should document in INSTALLATION.md that the binary packages for ARM require at least ARMv7 CPUs. This issue is a documentation error. Will try to change the title.

Maybe we can also detect in ./configure when the CPU is ARMv6 and then not include `-mcpu=cortex-a8` in the compiler options.

**Comment by MikeBarcl** [comment]
Hi Tobias,

Many thanks for your reply.

Do you foresee any difficulties if I compile for the pi zero, in terms of functionality?

I'm wondering about whether to go down this course or just get a better little computer.

Cheers
Mike

**Comment by tobiasherzke** [comment]
I cannot estimate how well the Zero's CPU will perform in floating-point signal processing tasks. You can try and see if it meets your requirements.

**Comment by tobiasherzke** [comment]
Commit 9a95cb4 fixes this documentation issue, is available now in branch development, and will be part of the upcoming release 4.14.0.
