### ISSUE TITLE
Installation on CentOS

### ISSUE THREAD

**Issue by mpariente** [HoerTech-gGmbH/openMHA#48]
Thanks a lot for this tool, it looks great! 

Is there a simple way to install it on CentOS, without sudo rights? 
Thanks in advance

**Comment by pmaanen** [comment]
Hi Manuel,
you can always compile openMHA yourself. See [COMPILATION.md](https://github.com/HoerTech-gGmbH/openMHA/blob/master/COMPILATION.md) on how to do this. Use the instructions for Linux, they _should_ work. You might have to look up the package names of the prerequisite libraries for `yum` but otherwise the compilation process should be straightforward. We do not have binary packages for centOS, sorry.

**Comment by mpariente** [comment]
Thank you, Paul!

> You might have to look up the package names of the prerequisite libraries for `yum`

This is the step I'm having trouble with. Do you have a resource where I can find the equivalence?

**Comment by pmaanen** [comment]
This is what I found by playing around in a Docker image. Your mileage may vary. You need to enable the PowerTools and EPEL repositories, then `yum install gcc make libsndfile-dev jack-audio-connection-kit-devel portaudio-devel eigen3-devel`. But without sudo rights you can not install these libraries with `yum`. I recommend you talk to your system administrator to get them to install these libraries. If you want to do real time I/O, you may need more permissions than a normal user anyway.

**Comment by mpariente** [comment]
I'll try that, thanks a lot !

**Comment by tobiasherzke** [comment]
I am closing this thread as it does not describe an open issue with openMHA. Please feel welcome to share your solution for installing openMHA on CentOS or your next steps on the openMHA forum! https://forum.openmha.org/
